"""Initial Migration

Revision ID: 054b78f0ed46
Revises: 381fd820a4a1
Create Date: 2021-03-07 19:37:19.466861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054b78f0ed46'
down_revision = '381fd820a4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_pitches_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'pitch', ['pitch_id'], ['id'])
    op.drop_column('comments', 'pitches_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitches_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_pitches_id_fkey', 'comments', 'pitch', ['pitches_id'], ['id'])
    op.drop_column('comments', 'pitch_id')
    # ### end Alembic commands ###
